views:
  v1/pods:
    columns:
      - NAME
      - STATUS
      - READY
      - RESTARTS
      - LAST RESTART|W
      - AGE
      - CPU/RL|S
      - MEM/RL|S
      - "%MEM/R"
      - "%CPU/R"
      - CPU
      - MEM
      - PF|H
      - "%MEM/L|H"
      - "%CPU/L|H"
  v1/nodes:
    columns:
      - NAME
      - STATUS
      - VERSION
      - PODS
      - AGE
