[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#333340"
blue = "#85d3e9"
cyan = "#8fb2ae"
green = "#ceebb0"
magenta = "#cf9ebe"
red = "#cf808c"
white = "#FFFFFF"
yellow = "#ebe6a9"

[colors.hints.end]
background = "0x000000"
foreground = "0x00ffff"

[colors.hints.start]
background = "0x00ffff"
foreground = "0x000000"

[colors.normal]
black = "#222228"
blue = "#499cb3"
cyan = "#62739e"
green = "#acce8e"
magenta = "#48547a"
red = "#de4e5c"
white = "#bebebe"
yellow = "#d7af87"

[colors.primary]
background = "#272730"
foreground = "#ffffff"

[font]
size = 16

[font.normal]
family = "Lilex Nerd Font Propo"
style = "Regular"

[font.offset]
x = 0
y = -1

[[hints.enabled]]
action = "Copy"
post_processing = false
regex = '([0-9a-f]{6,128})|([[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3})'

[hints.enabled.binding]
key = "Y"
mods = "Alt"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Alt"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
command = "open_jira.sh"
post_processing = true
regex = "(DO|AR)-[[:digit:]]+"

[hints.enabled.binding]
key = "U"
mods = "Alt|Shift"

[window]
opacity = 0.85
blur = true
decorations = "Buttonless"

[window.padding]
x = 2
y = 2
