# ~/.zshrc

# oh my zsh configuration
export ZSH=$HOME/.oh-my-zsh
plugins=(vi-mode kubectl fzf zoxide starship fast-syntax-highlighting command-not-found python)

# fzf options for zoxide
export _ZO_FZF_OPTS="--bind=ctrl-z:ignore \
    -i \
    --exit-0 \
    --height=35% \
    --inline-info \
    --no-sort \
    --reverse \
    --select-1"

# auto venv for python
export PYTHON_AUTO_VRUN=true

# esc-v vi bind
autoload -U edit-command-line 
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# bind C-K to kubectx
zle -N kubectx-k
function kubectx-k {
  kubectx < $TTY
  zle redisplay
  zle reset-prompt
}
bindkey '^K' kubectx-k

# get nix paths sourced
if [[ -f ~/.nix-profile/etc/profile.d/hm-session-vars.sh ]]; then
  source ~/.nix-profile/etc/profile.d/hm-session-vars.sh
fi

if [[ -f ~/.nix-profile/etc/profile.d/nix.sh ]]; then
  source ~/.nix-profile/etc/profile.d/nix.sh
fi

# oh my zsh init
source $ZSH/oh-my-zsh.sh

# initialize atuin
# eval "$(atuin init zsh)"

# enable completion on first tab press, needs to be after OMZ loads
setopt menu_complete

# get fancy LS COLORS going
export LS_COLORS=$(vivid generate jellybeans)

# alias time
alias ls="eza"
alias lltr="eza -lbhF -s modified"
alias ll="eza -lbhF --git"
alias gco="git branch -vv --sort=-committerdate | sed 's/* //g;s/^ *//g' | fzf --height=50% --info=inline | awk '{ print \$1 }' | xargs git checkout"
alias rg="rg --hidden --glob '!.git'"
alias ncdu="ncdu --color=dark"

# add additional PATH variables
if [[ -d ~/.cargo/bin ]]; then
  export PATH=$HOME/.cargo/bin:$PATH
fi

if [[ -d ~/bin ]]; then
  export PATH=$HOME/bin:$PATH
fi

# a terminal without a fortune is just sad
fortune-kind
